### ISSUE TITLE
UART RX interrupt example

### ISSUE THREAD

**Issue by homewsn** [asrlora/asr_lora_6601#1]
First, thanks for giving the opportunity to review the ASR6601 SDK.

I have a specific question about the operation of the UART in the mode of receiving bytes by interrupt. Unfortunately, I did not find such an example. The test project I implemented generally works, but for some reason the RX_DONE flag of the MIS register is not set when the interrupt handler is called after receiving a byte, although IMSC RX_DONE is 1 and an interrupt occurs.

**Comment by homewsn** [comment]
Sorry, it's working fine. Just the debugger reads the UART data register and clears the RX_DONE flag in front of me :)

But, by the way, are you sure that the [UART_CR_UART_MODE](https://github.com/asrlora/asr_lora_6601/blob/master/drivers/peripheral/inc/tremo_regs.h#L527) macro and the subsequent ones in this group are correct? It seems the correct value should be 0x300 etc.

**Comment by RuilinHao** [comment]
Yes, you are right. It should be 0x300. Thanks very much. For the uart rx interrupts, you can take a look at the ota/dongle example.
